import Head from "next/head";
import styles from "../styles/index.module.scss";
import Link from "next/link";
import Layout from "../layout";

export default function Home() {
    return (
        <Layout>
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className={styles.title}>
                        Welcome to <a href="https://nextjs.org">Next.js!</a>
                    </h1>

                    <p className={styles.description}>
                        Get started by editing{" "}
                        <code className={styles.code}>pages/index.js</code>
                    </p>

                    <div className={styles.grid}>
                        <Link href="/documentation" passHref>
                            <div className={styles.card}>
                                <h2>Documentation &rarr;</h2>
                                <p>
                                    Find in-depth information about Next.js
                                    features and API.
                                </p>
                            </div>
                        </Link>

                        <Link href="/learn" passHref>
                            <div className={styles.card}>
                                <h2>Learn &rarr;</h2>
                                <p>
                                    Learn about Next.js in an interactive course
                                    with quizzes!
                                </p>
                            </div>
                        </Link>

                        <Link href="/examples" passHref>
                            <div className={styles.card}>
                                <h2>Examples &rarr;</h2>
                                <p>
                                    Discover and deploy boilerplate example
                                    Next.js projects.
                                </p>
                            </div>
                        </Link>

                        <Link href="/deploy" passHref>
                            <div className={styles.card}>
                                <h2>Deploy &rarr;</h2>
                                <p>
                                    Instantly deploy your Next.js site to a
                                    public URL with Vercel.
                                </p>
                            </div>
                        </Link>
                        
                    </div>
                </main>
            </div>
        </Layout>
    );
}
